-- First, remove the table if it exists
drop table if exists customers;

-- Creat the table anew
create table customers (
    id INTEGER primary key generated by default as identity,
    customer_name text,
    phone VARCHAR(30)
);

-- insert some test data
-- Using a multi row insert statement
insert into customers (customer_name, phone)
values
    ('Sam', '555-1234'),
    ('Ham', '555-4321'),
    ('Ram', '666-1234');